// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

package com.ling.proto;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ResultMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * <pre>
   * 结果
   * </pre>
   *
   * Protobuf type {@code proto.ResultMessage}
   */
  public  static final class ResultMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ResultMessage)
      ResultMessageOrBuilder {
    // Use ResultMessage.newBuilder() to construct.
    private ResultMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultMessage() {
      code_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResultMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ling.proto.Command.internal_static_proto_ResultMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ling.proto.Command.internal_static_proto_ResultMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ling.proto.Command.ResultMessage.class, com.ling.proto.Command.ResultMessage.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>optional int32 code = 1;</code>
     */
    @Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    @Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ling.proto.Command.ResultMessage)) {
        return super.equals(obj);
      }
      com.ling.proto.Command.ResultMessage other = (com.ling.proto.Command.ResultMessage) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ling.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ling.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ling.proto.Command.ResultMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ling.proto.Command.ResultMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ling.proto.Command.ResultMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.ResultMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ling.proto.Command.ResultMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.ResultMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ling.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ling.proto.Command.ResultMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 结果
     * </pre>
     *
     * Protobuf type {@code proto.ResultMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ResultMessage)
        com.ling.proto.Command.ResultMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ling.proto.Command.internal_static_proto_ResultMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ling.proto.Command.internal_static_proto_ResultMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ling.proto.Command.ResultMessage.class, com.ling.proto.Command.ResultMessage.Builder.class);
      }

      // Construct using com.ling.proto.Command.ResultMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ling.proto.Command.internal_static_proto_ResultMessage_descriptor;
      }

      public com.ling.proto.Command.ResultMessage getDefaultInstanceForType() {
        return com.ling.proto.Command.ResultMessage.getDefaultInstance();
      }

      public com.ling.proto.Command.ResultMessage build() {
        com.ling.proto.Command.ResultMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ling.proto.Command.ResultMessage buildPartial() {
        com.ling.proto.Command.ResultMessage result = new com.ling.proto.Command.ResultMessage(this);
        result.code_ = code_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ling.proto.Command.ResultMessage) {
          return mergeFrom((com.ling.proto.Command.ResultMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ling.proto.Command.ResultMessage other) {
        if (other == com.ling.proto.Command.ResultMessage.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ling.proto.Command.ResultMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ling.proto.Command.ResultMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 1;</code>
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      @Override
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ResultMessage)
    }

    // @@protoc_insertion_point(class_scope:proto.ResultMessage)
    private static final com.ling.proto.Command.ResultMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ling.proto.Command.ResultMessage();
    }

    public static com.ling.proto.Command.ResultMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResultMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResultMessage>() {
      public ResultMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResultMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResultMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResultMessage> getParserForType() {
      return PARSER;
    }

    public com.ling.proto.Command.ResultMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Package)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 结果
     * </pre>
     *
     * <code>optional .proto.ResultMessage resultMsg = 1;</code>
     */
    boolean hasResultMsg();
    /**
     * <pre>
     * 结果
     * </pre>
     *
     * <code>optional .proto.ResultMessage resultMsg = 1;</code>
     */
    com.ling.proto.Command.ResultMessage getResultMsg();
    /**
     * <pre>
     * 结果
     * </pre>
     *
     * <code>optional .proto.ResultMessage resultMsg = 1;</code>
     */
    com.ling.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder();

    /**
     * <pre>
     * 指令类型
     * </pre>
     *
     * <code>optional int32 cmdType = 2;</code>
     */
    int getCmdType();

    /**
     * <pre>
     * 内容的二进制
     * </pre>
     *
     * <code>optional bytes content = 3;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * <pre>
   * 消息包，可以是请求包，可以是响应包
   * </pre>
   *
   * Protobuf type {@code proto.Package}
   */
  public  static final class Package extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Package)
      PackageOrBuilder {
    // Use Package.newBuilder() to construct.
    private Package(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Package() {
      cmdType_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Package(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.ling.proto.Command.ResultMessage.Builder subBuilder = null;
              if (resultMsg_ != null) {
                subBuilder = resultMsg_.toBuilder();
              }
              resultMsg_ = input.readMessage(com.ling.proto.Command.ResultMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resultMsg_);
                resultMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              cmdType_ = input.readInt32();
              break;
            }
            case 26: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ling.proto.Command.internal_static_proto_Package_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ling.proto.Command.internal_static_proto_Package_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ling.proto.Command.Package.class, com.ling.proto.Command.Package.Builder.class);
    }

    public static final int RESULTMSG_FIELD_NUMBER = 1;
    private com.ling.proto.Command.ResultMessage resultMsg_;
    /**
     * <pre>
     * 结果
     * </pre>
     *
     * <code>optional .proto.ResultMessage resultMsg = 1;</code>
     */
    public boolean hasResultMsg() {
      return resultMsg_ != null;
    }
    /**
     * <pre>
     * 结果
     * </pre>
     *
     * <code>optional .proto.ResultMessage resultMsg = 1;</code>
     */
    public com.ling.proto.Command.ResultMessage getResultMsg() {
      return resultMsg_ == null ? com.ling.proto.Command.ResultMessage.getDefaultInstance() : resultMsg_;
    }
    /**
     * <pre>
     * 结果
     * </pre>
     *
     * <code>optional .proto.ResultMessage resultMsg = 1;</code>
     */
    public com.ling.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder() {
      return getResultMsg();
    }

    public static final int CMDTYPE_FIELD_NUMBER = 2;
    private int cmdType_;
    /**
     * <pre>
     * 指令类型
     * </pre>
     *
     * <code>optional int32 cmdType = 2;</code>
     */
    public int getCmdType() {
      return cmdType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     * 内容的二进制
     * </pre>
     *
     * <code>optional bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resultMsg_ != null) {
        output.writeMessage(1, getResultMsg());
      }
      if (cmdType_ != 0) {
        output.writeInt32(2, cmdType_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(3, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resultMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResultMsg());
      }
      if (cmdType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cmdType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ling.proto.Command.Package)) {
        return super.equals(obj);
      }
      com.ling.proto.Command.Package other = (com.ling.proto.Command.Package) obj;

      boolean result = true;
      result = result && (hasResultMsg() == other.hasResultMsg());
      if (hasResultMsg()) {
        result = result && getResultMsg()
            .equals(other.getResultMsg());
      }
      result = result && (getCmdType()
          == other.getCmdType());
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResultMsg()) {
        hash = (37 * hash) + RESULTMSG_FIELD_NUMBER;
        hash = (53 * hash) + getResultMsg().hashCode();
      }
      hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCmdType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ling.proto.Command.Package parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ling.proto.Command.Package parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ling.proto.Command.Package parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ling.proto.Command.Package parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ling.proto.Command.Package parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.Package parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ling.proto.Command.Package parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.Package parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ling.proto.Command.Package parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.Package parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ling.proto.Command.Package prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息包，可以是请求包，可以是响应包
     * </pre>
     *
     * Protobuf type {@code proto.Package}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Package)
        com.ling.proto.Command.PackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ling.proto.Command.internal_static_proto_Package_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ling.proto.Command.internal_static_proto_Package_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ling.proto.Command.Package.class, com.ling.proto.Command.Package.Builder.class);
      }

      // Construct using com.ling.proto.Command.Package.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (resultMsgBuilder_ == null) {
          resultMsg_ = null;
        } else {
          resultMsg_ = null;
          resultMsgBuilder_ = null;
        }
        cmdType_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ling.proto.Command.internal_static_proto_Package_descriptor;
      }

      public com.ling.proto.Command.Package getDefaultInstanceForType() {
        return com.ling.proto.Command.Package.getDefaultInstance();
      }

      public com.ling.proto.Command.Package build() {
        com.ling.proto.Command.Package result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ling.proto.Command.Package buildPartial() {
        com.ling.proto.Command.Package result = new com.ling.proto.Command.Package(this);
        if (resultMsgBuilder_ == null) {
          result.resultMsg_ = resultMsg_;
        } else {
          result.resultMsg_ = resultMsgBuilder_.build();
        }
        result.cmdType_ = cmdType_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ling.proto.Command.Package) {
          return mergeFrom((com.ling.proto.Command.Package)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ling.proto.Command.Package other) {
        if (other == com.ling.proto.Command.Package.getDefaultInstance()) return this;
        if (other.hasResultMsg()) {
          mergeResultMsg(other.getResultMsg());
        }
        if (other.getCmdType() != 0) {
          setCmdType(other.getCmdType());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ling.proto.Command.Package parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ling.proto.Command.Package) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.ling.proto.Command.ResultMessage resultMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ling.proto.Command.ResultMessage, com.ling.proto.Command.ResultMessage.Builder, com.ling.proto.Command.ResultMessageOrBuilder> resultMsgBuilder_;
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      public boolean hasResultMsg() {
        return resultMsgBuilder_ != null || resultMsg_ != null;
      }
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      @Override
      public com.ling.proto.Command.ResultMessage getResultMsg() {
        if (resultMsgBuilder_ == null) {
          return resultMsg_ == null ? com.ling.proto.Command.ResultMessage.getDefaultInstance() : resultMsg_;
        } else {
          return resultMsgBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder setResultMsg(com.ling.proto.Command.ResultMessage value) {
        if (resultMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resultMsg_ = value;
          onChanged();
        } else {
          resultMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder setResultMsg(
          com.ling.proto.Command.ResultMessage.Builder builderForValue) {
        if (resultMsgBuilder_ == null) {
          resultMsg_ = builderForValue.build();
          onChanged();
        } else {
          resultMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder mergeResultMsg(com.ling.proto.Command.ResultMessage value) {
        if (resultMsgBuilder_ == null) {
          if (resultMsg_ != null) {
            resultMsg_ =
              com.ling.proto.Command.ResultMessage.newBuilder(resultMsg_).mergeFrom(value).buildPartial();
          } else {
            resultMsg_ = value;
          }
          onChanged();
        } else {
          resultMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder clearResultMsg() {
        if (resultMsgBuilder_ == null) {
          resultMsg_ = null;
          onChanged();
        } else {
          resultMsg_ = null;
          resultMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      public com.ling.proto.Command.ResultMessage.Builder getResultMsgBuilder() {
        
        onChanged();
        return getResultMsgFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      public com.ling.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder() {
        if (resultMsgBuilder_ != null) {
          return resultMsgBuilder_.getMessageOrBuilder();
        } else {
          return resultMsg_ == null ?
              com.ling.proto.Command.ResultMessage.getDefaultInstance() : resultMsg_;
        }
      }
      /**
       * <pre>
       * 结果
       * </pre>
       *
       * <code>optional .proto.ResultMessage resultMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ling.proto.Command.ResultMessage, com.ling.proto.Command.ResultMessage.Builder, com.ling.proto.Command.ResultMessageOrBuilder> 
          getResultMsgFieldBuilder() {
        if (resultMsgBuilder_ == null) {
          resultMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ling.proto.Command.ResultMessage, com.ling.proto.Command.ResultMessage.Builder, com.ling.proto.Command.ResultMessageOrBuilder>(
                  getResultMsg(),
                  getParentForChildren(),
                  isClean());
          resultMsg_ = null;
        }
        return resultMsgBuilder_;
      }

      private int cmdType_ ;
      /**
       * <pre>
       * 指令类型
       * </pre>
       *
       * <code>optional int32 cmdType = 2;</code>
       */
      public int getCmdType() {
        return cmdType_;
      }
      /**
       * <pre>
       * 指令类型
       * </pre>
       *
       * <code>optional int32 cmdType = 2;</code>
       */
      public Builder setCmdType(int value) {
        
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令类型
       * </pre>
       *
       * <code>optional int32 cmdType = 2;</code>
       */
      public Builder clearCmdType() {
        
        cmdType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 内容的二进制
       * </pre>
       *
       * <code>optional bytes content = 3;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       * 内容的二进制
       * </pre>
       *
       * <code>optional bytes content = 3;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容的二进制
       * </pre>
       *
       * <code>optional bytes content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Package)
    }

    // @@protoc_insertion_point(class_scope:proto.Package)
    private static final com.ling.proto.Command.Package DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ling.proto.Command.Package();
    }

    public static com.ling.proto.Command.Package getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Package>
        PARSER = new com.google.protobuf.AbstractParser<Package>() {
      public Package parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Package(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Package> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Package> getParserForType() {
      return PARSER;
    }

    public com.ling.proto.Command.Package getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackageGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PackageGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    java.util.List<com.ling.proto.Command.Package> 
        getPackagesList();
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    com.ling.proto.Command.Package getPackages(int index);
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    int getPackagesCount();
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    java.util.List<? extends com.ling.proto.Command.PackageOrBuilder> 
        getPackagesOrBuilderList();
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    com.ling.proto.Command.PackageOrBuilder getPackagesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 多个消息包，网络协议中的封包（多个消息包一次传输）
   * </pre>
   *
   * Protobuf type {@code proto.PackageGroup}
   */
  public  static final class PackageGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PackageGroup)
      PackageGroupOrBuilder {
    // Use PackageGroup.newBuilder() to construct.
    private PackageGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageGroup() {
      packages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PackageGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                packages_ = new java.util.ArrayList<com.ling.proto.Command.Package>();
                mutable_bitField0_ |= 0x00000001;
              }
              packages_.add(
                  input.readMessage(com.ling.proto.Command.Package.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          packages_ = java.util.Collections.unmodifiableList(packages_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ling.proto.Command.internal_static_proto_PackageGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ling.proto.Command.internal_static_proto_PackageGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ling.proto.Command.PackageGroup.class, com.ling.proto.Command.PackageGroup.Builder.class);
    }

    public static final int PACKAGES_FIELD_NUMBER = 1;
    private java.util.List<com.ling.proto.Command.Package> packages_;
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    public java.util.List<com.ling.proto.Command.Package> getPackagesList() {
      return packages_;
    }
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    public java.util.List<? extends com.ling.proto.Command.PackageOrBuilder> 
        getPackagesOrBuilderList() {
      return packages_;
    }
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    public int getPackagesCount() {
      return packages_.size();
    }
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    public com.ling.proto.Command.Package getPackages(int index) {
      return packages_.get(index);
    }
    /**
     * <code>repeated .proto.Package packages = 1;</code>
     */
    public com.ling.proto.Command.PackageOrBuilder getPackagesOrBuilder(
        int index) {
      return packages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < packages_.size(); i++) {
        output.writeMessage(1, packages_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < packages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, packages_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ling.proto.Command.PackageGroup)) {
        return super.equals(obj);
      }
      com.ling.proto.Command.PackageGroup other = (com.ling.proto.Command.PackageGroup) obj;

      boolean result = true;
      result = result && getPackagesList()
          .equals(other.getPackagesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPackagesCount() > 0) {
        hash = (37 * hash) + PACKAGES_FIELD_NUMBER;
        hash = (53 * hash) + getPackagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ling.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ling.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ling.proto.Command.PackageGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ling.proto.Command.PackageGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ling.proto.Command.PackageGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.PackageGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ling.proto.Command.PackageGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.PackageGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ling.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ling.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ling.proto.Command.PackageGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 多个消息包，网络协议中的封包（多个消息包一次传输）
     * </pre>
     *
     * Protobuf type {@code proto.PackageGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PackageGroup)
        com.ling.proto.Command.PackageGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ling.proto.Command.internal_static_proto_PackageGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ling.proto.Command.internal_static_proto_PackageGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ling.proto.Command.PackageGroup.class, com.ling.proto.Command.PackageGroup.Builder.class);
      }

      // Construct using com.ling.proto.Command.PackageGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPackagesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (packagesBuilder_ == null) {
          packages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          packagesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ling.proto.Command.internal_static_proto_PackageGroup_descriptor;
      }

      public com.ling.proto.Command.PackageGroup getDefaultInstanceForType() {
        return com.ling.proto.Command.PackageGroup.getDefaultInstance();
      }

      public com.ling.proto.Command.PackageGroup build() {
        com.ling.proto.Command.PackageGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ling.proto.Command.PackageGroup buildPartial() {
        com.ling.proto.Command.PackageGroup result = new com.ling.proto.Command.PackageGroup(this);
        int from_bitField0_ = bitField0_;
        if (packagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            packages_ = java.util.Collections.unmodifiableList(packages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.packages_ = packages_;
        } else {
          result.packages_ = packagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ling.proto.Command.PackageGroup) {
          return mergeFrom((com.ling.proto.Command.PackageGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ling.proto.Command.PackageGroup other) {
        if (other == com.ling.proto.Command.PackageGroup.getDefaultInstance()) return this;
        if (packagesBuilder_ == null) {
          if (!other.packages_.isEmpty()) {
            if (packages_.isEmpty()) {
              packages_ = other.packages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePackagesIsMutable();
              packages_.addAll(other.packages_);
            }
            onChanged();
          }
        } else {
          if (!other.packages_.isEmpty()) {
            if (packagesBuilder_.isEmpty()) {
              packagesBuilder_.dispose();
              packagesBuilder_ = null;
              packages_ = other.packages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              packagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPackagesFieldBuilder() : null;
            } else {
              packagesBuilder_.addAllMessages(other.packages_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ling.proto.Command.PackageGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ling.proto.Command.PackageGroup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ling.proto.Command.Package> packages_ =
        java.util.Collections.emptyList();
      private void ensurePackagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          packages_ = new java.util.ArrayList<com.ling.proto.Command.Package>(packages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ling.proto.Command.Package, com.ling.proto.Command.Package.Builder, com.ling.proto.Command.PackageOrBuilder> packagesBuilder_;

      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public java.util.List<com.ling.proto.Command.Package> getPackagesList() {
        if (packagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(packages_);
        } else {
          return packagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public int getPackagesCount() {
        if (packagesBuilder_ == null) {
          return packages_.size();
        } else {
          return packagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public com.ling.proto.Command.Package getPackages(int index) {
        if (packagesBuilder_ == null) {
          return packages_.get(index);
        } else {
          return packagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder setPackages(
          int index, com.ling.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.set(index, value);
          onChanged();
        } else {
          packagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder setPackages(
          int index, com.ling.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.set(index, builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder addPackages(com.ling.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.add(value);
          onChanged();
        } else {
          packagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          int index, com.ling.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.add(index, value);
          onChanged();
        } else {
          packagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          com.ling.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.add(builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          int index, com.ling.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.add(index, builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder addAllPackages(
          java.lang.Iterable<? extends com.ling.proto.Command.Package> values) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, packages_);
          onChanged();
        } else {
          packagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder clearPackages() {
        if (packagesBuilder_ == null) {
          packages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          packagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public Builder removePackages(int index) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.remove(index);
          onChanged();
        } else {
          packagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public com.ling.proto.Command.Package.Builder getPackagesBuilder(
          int index) {
        return getPackagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public com.ling.proto.Command.PackageOrBuilder getPackagesOrBuilder(
          int index) {
        if (packagesBuilder_ == null) {
          return packages_.get(index);  } else {
          return packagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public java.util.List<? extends com.ling.proto.Command.PackageOrBuilder> 
           getPackagesOrBuilderList() {
        if (packagesBuilder_ != null) {
          return packagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(packages_);
        }
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public com.ling.proto.Command.Package.Builder addPackagesBuilder() {
        return getPackagesFieldBuilder().addBuilder(
            com.ling.proto.Command.Package.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public com.ling.proto.Command.Package.Builder addPackagesBuilder(
          int index) {
        return getPackagesFieldBuilder().addBuilder(
            index, com.ling.proto.Command.Package.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Package packages = 1;</code>
       */
      public java.util.List<com.ling.proto.Command.Package.Builder> 
           getPackagesBuilderList() {
        return getPackagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ling.proto.Command.Package, com.ling.proto.Command.Package.Builder, com.ling.proto.Command.PackageOrBuilder> 
          getPackagesFieldBuilder() {
        if (packagesBuilder_ == null) {
          packagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ling.proto.Command.Package, com.ling.proto.Command.Package.Builder, com.ling.proto.Command.PackageOrBuilder>(
                  packages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          packages_ = null;
        }
        return packagesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PackageGroup)
    }

    // @@protoc_insertion_point(class_scope:proto.PackageGroup)
    private static final com.ling.proto.Command.PackageGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ling.proto.Command.PackageGroup();
    }

    public static com.ling.proto.Command.PackageGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackageGroup>
        PARSER = new com.google.protobuf.AbstractParser<PackageGroup>() {
      public PackageGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PackageGroup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageGroup> getParserForType() {
      return PARSER;
    }

    public com.ling.proto.Command.PackageGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResultMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ResultMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Package_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Package_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PackageGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PackageGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCmd.proto\022\005proto\"*\n\rResultMessage\022\014\n\004c" +
      "ode\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\"T\n\007Package\022\'\n\tres" +
      "ultMsg\030\001 \001(\0132\024.proto.ResultMessage\022\017\n\007cm" +
      "dType\030\002 \001(\005\022\017\n\007content\030\003 \001(\014\"0\n\014PackageG" +
      "roup\022 \n\010packages\030\001 \003(\0132\016.proto.PackageB\035" +
      "\n\016com.ling.protoB\007CommandH\001P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ResultMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ResultMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ResultMessage_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_proto_Package_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Package_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Package_descriptor,
        new java.lang.String[] { "ResultMsg", "CmdType", "Content", });
    internal_static_proto_PackageGroup_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_PackageGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PackageGroup_descriptor,
        new java.lang.String[] { "Packages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
